name: "fibonacci Action"
description: "Fibo series Action"
author: "ronaldoc@uninorte.edu.co"
 
inputs:
  MY_NAME:
    description: "show fibonacci"
    required: true
    default: "fibo series"
 
runs:
  using: "docker"
  image: "Dockerfile"